// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gxodvquaonfkfgretpad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd4b2R2cXVhb25ma2ZncmV0cGFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTc0NjIsImV4cCI6MjA2NTQ5MzQ2Mn0.hXqmdfAncIwVhl1j4vn2AmD3ttFVwB1d6VLoW0sH-os";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);